### ISSUE TITLE
w.plot method fails in turial 3

### ISSUE THREAD

**Issue by adantra** [andymcdgeo/Petrophysics-Python-Series#2]
in tutorial 3: the following lines produce an error.

tracks = ['MD','strip', 'GR', 'RHOB', ['DT', 'DTS'], 'M2R9', 'MD']
w.plot(tracks=tracks, legend=legend)

The following works:
tracks = ['strip', 'GR', 'RHOB', ['DT', 'DTS'], 'M2R9']
w.plot(tracks=tracks, legend=legend)

but then, I cannot see the depth track. Am I missing something?

**Comment by andymcdgeo** [comment]
This issue doesn't appear to relate to Notebook 3 within this series.
If the issue persists, please open a new case with further details.
